const LIST = [
    { emoji: "👌🏿", tags: ['Ok'] },
    { emoji: "👌🏾", tags: ['Ok'] },
    { emoji: "👌🏽", tags: ['Ok'] },
    { emoji: "👌🏼", tags: ['Ok'] },
    { emoji: "👌🏻", tags: ['Ok'] },
    { emoji: "👌", tags: ['Ok'] },
    { emoji: "👍🏿", tags: ['Thumbs Up', 'Like', 'Positive', 'Affirmative', 'Yes', 'Accept'] },
    { emoji: "👍🏾", tags: ['Thumbs Up', 'Like', 'Positive', 'Affirmative', 'Yes', 'Accept'] },
    { emoji: "👍🏽", tags: ['Thumbs Up', 'Like', 'Positive', 'Affirmative', 'Yes', 'Accept'] },
    { emoji: "👍🏼", tags: ['Thumbs Up', 'Like', 'Positive', 'Affirmative', 'Yes', 'Accept'] },
    { emoji: "👍🏻", tags: ['Thumbs Up', 'Like', 'Positive', 'Affirmative', 'Yes', 'Accept'] },
    { emoji: "👍", tags: ['Thumbs Up', 'Like', 'Positive', 'Affirmative', 'Yes', 'Accept'] },
    { emoji: "👎🏿", tags: ['Thumbs Down', 'Negative', 'No', 'Decline'] },
    { emoji: "👎🏾", tags: ['Thumbs Down', 'Negative', 'No', 'Decline'] },
    { emoji: "👎🏽", tags: ['Thumbs Down', 'Negative', 'No', 'Decline'] },
    { emoji: "👎🏼", tags: ['Thumbs Down', 'Negative', 'No', 'Decline'] },
    { emoji: "👎🏻", tags: ['Thumbs Down', 'Negative', 'No', 'Decline'] },
    { emoji: "👎", tags: ['Thumbs Down', 'Negative', 'No', 'Decline'] },
    { emoji: "🙏🏿", tags: ['Folded Hands', 'Grace'] },
    { emoji: "🙏🏾", tags: ['Folded Hands', 'Grace'] },
    { emoji: "🙏🏽", tags: ['Folded Hands', 'Grace'] },
    { emoji: "🙏🏼", tags: ['Folded Hands', 'Grace'] },
    { emoji: "🙏🏻", tags: ['Folded Hands', 'Grace'] },
    { emoji: "🙏", tags: ['Folded Hands', 'Grace'] },
    { emoji: "🙌🏿", tags: ['Raised Hands', 'Hands Up'] },
    { emoji: "🙌🏾", tags: ['Raised Hands', 'Hands Up'] },
    { emoji: "🙌🏽", tags: ['Raised Hands', 'Hands Up'] },
    { emoji: "🙌🏼", tags: ['Raised Hands', 'Hands Up'] },
    { emoji: "🙌🏻", tags: ['Raised Hands', 'Hands Up'] },
    { emoji: "🙌", tags: ['Raised Hands', 'Hands Up'] },
    { emoji: "✌🏿", tags: ['Victory Hand', 'Peace'] },
    { emoji: "✌🏾", tags: ['Victory Hand', 'Peace'] },
    { emoji: "✌🏽", tags: ['Victory Hand', 'Peace'] },
    { emoji: "✌🏼", tags: ['Victory Hand', 'Peace'] },
    { emoji: "✌🏻", tags: ['Victory Hand', 'Peace'] },
    { emoji: "✌️", tags: ['Victory Hand', 'Peace'] },
    { emoji: "👏🏿", tags: ['Clapping Hands', 'Clap'] },
    { emoji: "👏🏾", tags: ['Clapping Hands', 'Clap'] },
    { emoji: "👏🏽", tags: ['Clapping Hands', 'Clap'] },
    { emoji: "👏🏼", tags: ['Clapping Hands', 'Clap'] },
    { emoji: "👏🏻", tags: ['Clapping Hands', 'Clap'] },
    { emoji: "👏", tags: ['Clapping Hands', 'Clap'] },
    { emoji: "✋🏿", tags: ['Raised Hand', 'Stop'] },
    { emoji: "✋🏾", tags: ['Raised Hand', 'Stop'] },
    { emoji: "✋🏽", tags: ['Raised Hand', 'Stop'] },
    { emoji: "✋🏼", tags: ['Raised Hand', 'Stop'] },
    { emoji: "✋🏻", tags: ['Raised Hand', 'Stop'] },
    { emoji: "✋", tags: ['Raised Hand', 'Stop'] },
    { emoji: "👉🏿", tags: ['Right Pointer'] },
    { emoji: "👉🏾", tags: ['Right Pointer'] },
    { emoji: "👉🏽", tags: ['Right Pointer'] },
    { emoji: "👉🏼", tags: ['Right Pointer'] },
    { emoji: "👉🏻", tags: ['Right Pointer'] },
    { emoji: "👉", tags: ['Right Pointer'] },
    { emoji: "👈🏿", tags: ['Left Pointer'] },
    { emoji: "👈🏾", tags: ['Left Pointer'] },
    { emoji: "👈🏽", tags: ['Left Pointer'] },
    { emoji: "👈🏼", tags: ['Left Pointer'] },
    { emoji: "👈🏻", tags: ['Left Pointer'] },
    { emoji: "👈", tags: ['Left Pointer'] },
    { emoji: "👇🏿", tags: ['Thumbs Down'] },
    { emoji: "👇🏾", tags: ['Thumbs Down'] },
    { emoji: "👇🏽", tags: ['Thumbs Down'] },
    { emoji: "👇🏼", tags: ['Thumbs Down'] },
    { emoji: "👇🏻", tags: ['Thumbs Down'] },
    { emoji: "👇", tags: ['Thumbs Down'] },
    { emoji: "👆🏿", tags: ['Thumbs Up'] },
    { emoji: "👆🏾", tags: ['Thumbs Up'] },
    { emoji: "👆🏽", tags: ['Thumbs Up'] },
    { emoji: "👆🏼", tags: ['Thumbs Up'] },
    { emoji: "👆🏻", tags: ['Thumbs Up'] },
    { emoji: "👆", tags: ['Thumbs Up'] },
    { emoji: "☝🏿", tags: ['White Up', 'Indicator'] },
    { emoji: "☝🏾", tags: ['White Up', 'Indicator'] },
    { emoji: "☝🏽", tags: ['White Up', 'Indicator'] },
    { emoji: "☝🏼", tags: ['White Up', 'Indicator'] },
    { emoji: "☝🏻", tags: ['White Up', 'Indicator'] },
    { emoji: "☝️", tags: ['White Up', 'Indicator'] },
    { emoji: "👊🏿", tags: ['Fisted Hand', 'Punch'] },
    { emoji: "👊🏾", tags: ['Fisted Hand', 'Punch'] },
    { emoji: "👊🏽", tags: ['Fisted Hand', 'Punch'] },
    { emoji: "👊🏼", tags: ['Fisted Hand', 'Punch'] },
    { emoji: "👊🏻", tags: ['Fisted Hand', 'Punch'] },
    { emoji: "👊", tags: ['Fisted Hand', 'Punch'] },
    { emoji: "💪🏿", tags: ['Flexed Biceps', 'Strong', 'Muscle'] },
    { emoji: "💪🏾", tags: ['Flexed Biceps', 'Strong', 'Muscle'] },
    { emoji: "💪🏽", tags: ['Flexed Biceps', 'Strong', 'Muscle'] },
    { emoji: "💪🏼", tags: ['Flexed Biceps', 'Strong', 'Muscle'] },
    { emoji: "💪🏻", tags: ['Flexed Biceps', 'Strong', 'Muscle'] },
    { emoji: "💪", tags: ['Flexed Biceps', 'Strong', 'Muscle'] },
    { emoji: "👋🏿", tags: ['Waving Hands', 'Hello'] },
    { emoji: "👋🏾", tags: ['Waving Hands', 'Hello'] },
    { emoji: "👋🏽", tags: ['Waving Hands', 'Hello'] },
    { emoji: "👋🏼", tags: ['Waving Hands', 'Hello'] },
    { emoji: "👋🏻", tags: ['Waving Hands', 'Hello'] },
    { emoji: "👋", tags: ['Waving Hands', 'Hello'] },
    { emoji: "✊🏿", tags: ['Raised Fist'] },
    { emoji: "✊🏾", tags: ['Raised Fist'] },
    { emoji: "✊🏽", tags: ['Raised Fist'] },
    { emoji: "✊🏼", tags: ['Raised Fist'] },
    { emoji: "✊🏻", tags: ['Raised Fist'] },
    { emoji: "✊", tags: ['Raised Fist'] },
    { emoji: "👐🏿", tags: ['Open Hands'] },
    { emoji: "👐🏾", tags: ['Open Hands'] },
    { emoji: "👐🏽", tags: ['Open Hands'] },
    { emoji: "👐🏼", tags: ['Open Hands'] },
    { emoji: "👐🏻", tags: ['Open Hands'] },
    { emoji: "👐", tags: ['Open Hands'] },
    { emoji: "🤘🏿", tags: ['Horns', 'Rock'] },
    { emoji: "🤘🏾", tags: ['Horns', 'Rock'] },
    { emoji: "🤘🏽", tags: ['Horns', 'Rock'] },
    { emoji: "🤘🏼", tags: ['Horns', 'Rock'] },
    { emoji: "🤘🏻", tags: ['Horns', 'Rock'] },
    { emoji: "🤘", tags: ['Horns', 'Rock'] },
    { emoji: "🖖🏿", tags: ['Vulcan Salute'] },
    { emoji: "🖖🏾", tags: ['Vulcan Salute'] },
    { emoji: "🖖🏽", tags: ['Vulcan Salute'] },
    { emoji: "🖖🏼", tags: ['Vulcan Salute'] },
    { emoji: "🖖🏻", tags: ['Vulcan Salute'] },
    { emoji: "🖖", tags: ['Vulcan Salute'] },
    { emoji: "🖕🏿", tags: ['Middle Finger', 'F*ck'] },
    { emoji: "🖕🏾", tags: ['Middle Finger', 'F*ck'] },
    { emoji: "🖕🏽", tags: ['Middle Finger', 'F*ck'] },
    { emoji: "🖕🏼", tags: ['Middle Finger', 'F*ck'] },
    { emoji: "🖕🏻", tags: ['Middle Finger', 'F*ck'] },
    { emoji: "🖕", tags: ['Middle Finger', 'F*ck'] },
    { emoji: "🖐🏿", tags: ['Raised Hand With Fingers Splayed'] },
    { emoji: "🖐🏾", tags: ['Raised Hand With Fingers Splayed'] },
    { emoji: "🖐🏽", tags: ['Raised Hand With Fingers Splayed'] },
    { emoji: "🖐🏼", tags: ['Raised Hand With Fingers Splayed'] },
    { emoji: "🖐🏻", tags: ['Raised Hand With Fingers Splayed'] },
    { emoji: "🖐", tags: ['Raised Hand With Fingers Splayed'] },
    { emoji: "✍🏿", tags: ['Writing Hand'] },
    { emoji: "✍🏾", tags: ['Writing Hand'] },
    { emoji: "✍🏽", tags: ['Writing Hand'] },
    { emoji: "✍🏼", tags: ['Writing Hand'] },
    { emoji: "✍🏻", tags: ['Writing Hand'] },
    { emoji: "✍", tags: ['Writing Hand'] },
    { emoji: "💅🏿", tags: ['Nail Polish'] },
    { emoji: "💅🏾", tags: ['Nail Polish'] },
    { emoji: "💅🏽", tags: ['Nail Polish'] },
    { emoji: "💅🏼", tags: ['Nail Polish'] },
    { emoji: "💅🏻", tags: ['Nail Polish'] },
    { emoji: "💅", tags: ['Nail Polish'] },
];

export const EMOJI_LIST = LIST;

export const getEmoji = (index) => ((LIST[index] && LIST[index].emoji) || '');